version: '3.5' 
services: 

  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=socialbot
    container_name: db
    volumes:
      - pgvolume:/var/lib/postgresql/data 
    ports:
      - '5432:5432' 
    networks:
      - backend-network

  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: app
    environment: 
      - NODE_ENV=development
    ports: 
      - '3000:3000' 
    depends_on: 
      - db 
    volumes:
        - .:/usr/src/app 
    networks:
      - backend-network

volumes:
  pgvolume:
    driver: local
networks:
    backend-network:
      driver: bridge