version: '3.5' 
services: 

  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=socialbot
    container_name: db
    volumes:
      - pgvolume:/var/lib/postgresql/data 
    ports:
      - '5432:5432' 
    networks:
      - backend-network

  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: app
    environment: 
      - NODE_ENV=development
    ports: 
      - '3000:3000' 
    depends_on: 
      - db 
    volumes:
        - .:/usr/src/app 
        - ./node_modules:/usr/src/app/node_modules
    networks:
      - backend-network

  # docs: 
  #   build: 
  #     context: . 
  #   container_name: doc
  #   ports: 
  #     - '8080:8080' 
  #   depends_on: 
  #     - app
  #   volumes:
  #       - ./src:/app/src 
  #   networks:
  #     - backend-network
  #   command: >
  #     /bin/sh -c "
  #     npx @compodoc/compodoc -p tsconfig.json -s
  #     "

  dbeaver:
    image: dbeaver/cloudbeaver
    # restart: always 
    container_name: bvr
    environment:
      - CB_ADMIN_NAME=dbeaver
      - CB_ADMIN_PASSWORD=Dbeaver1
    ports: 
      - '5050:8978' 
    depends_on: 
        - db
    networks:
      - backend-network

volumes:
  pgvolume:
    driver: local
networks:
    backend-network:
      driver: bridge