version: '3.5' 
services: 

  db: 
    image: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=socialbot
    container_name: db
    volumes:
      - pgvolume:/var/lib/postgresql/data 
    ports:
      - '5432:5432' 
    networks:
      - backend-network

  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-network

volumes:
  pgvolume:
    driver: local
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
networks:
    backend-network:
      driver: bridge