name: Discord Message

on:
  pull_request:
    types: [closed]

jobs:
  send-discord-message:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          ESCAPED_TITLE=$(echo "$PR_TITLE" | jq -Rr @json)
          ESCAPED_AUTHOR=$(echo "$PR_AUTHOR" | jq -Rr @json)
          ESCAPED_URL=$(echo "$PR_URL" | jq -Rr @json)
          ESCAPED_NUMBER=$(echo "$PR_NUMBER" | jq -Rr @json)
          ESCAPED_DESCRIPTION=$(echo "$PR_DESCRIPTION" | jq -Rr @json)

          echo "PR_TITLE: $PR_TITLE"
          echo "PR_AUTHOR: $PR_AUTHOR"
          echo "PR_URL: $PR_URL"
          echo "PR_NUMBER: $PR_NUMBER"
          echo "PR_DESCRIPTION: $PR_DESCRIPTION"

          echo "Escaped PR_TITLE: $ESCAPED_TITLE"
          echo "Escaped PR_AUTHOR: $ESCAPED_AUTHOR"
          echo "Escaped PR_URL: $ESCAPED_URL"
          echo "Escaped PR_NUMBER: $ESCAPED_NUMBER"
          echo "Escaped PR_DESCRIPTION: $ESCAPED_DESCRIPTION"
          
          EMBED_PAYLOAD=$(jq -n \
            --arg title "Pull Request #$ESCAPED_NUMBER Merged" \
            --arg description "$ESCAPED_DESCRIPTION" \
            --arg url "$ESCAPED_URL" \
            --arg author "$ESCAPED_AUTHOR" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "fields": [
                    {
                      "name": "Author",
                      "value": $author,
                      "inline": true
                    },
                    {
                      "name": "URL",
                      "value": $url,
                      "inline": true
                    }
                  ],
                  "color": 3066993
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
              -d "$EMBED_PAYLOAD" \
              "$DISCORD_WEBHOOK_URL"
        