name: Discord Message

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [closed]

jobs:
  send-discord-message:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          ESCAPED_TITLE=$(echo "$PR_TITLE" | jq -Rr @json)
          ESCAPED_AUTHOR=$(echo "$PR_AUTHOR" | jq -Rr @json)
          ESCAPED_URL=$(echo "$PR_URL" | jq -Rr @json)
          ESCAPED_NUMBER=$(echo "$PR_NUMBER" | jq -Rr @json)
          ESCAPED_DESCRIPTION=$(echo "$PR_DESCRIPTION" | jq -Rr @json)

          echo "PR_TITLE: $PR_TITLE"
          echo "PR_AUTHOR: $PR_AUTHOR"
          echo "PR_URL: $PR_URL"
          echo "PR_NUMBER: $PR_NUMBER"
          echo "PR_DESCRIPTION: $PR_DESCRIPTION"

          echo "Escaped PR_TITLE: $ESCAPED_TITLE"
          echo "Escaped PR_AUTHOR: $ESCAPED_AUTHOR"
          echo "Escaped PR_URL: $ESCAPED_URL"
          echo "Escaped PR_NUMBER: $ESCAPED_NUMBER"
          echo "Escaped PR_DESCRIPTION: $ESCAPED_DESCRIPTION"

          curl -H "Content-Type: application/json" \
          -d "{\"username\": $ESCAPED_AUTHOR, \"content\": \"📢 **Pull Request #$ESCAPED_NUMBER Merged**\n\n# Title: $ESCAPED_TITLE\n**Author:** $ESCAPED_AUTHOR\n**URL:** $ESCAPED_URL\n**DESCRIPTION:** $ESCAPED_DESCRIPTION\"}" \
          $DISCORD_WEBHOOK_URL