name: Discord Message

on:
  pull_request:
    types: [closed]

jobs:
  send-discord-message:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"  
          curl -H "Content-Type: application/json" \
               -d "{\"username\": \"$PR_AUTHOR\", \"content\": \"
               📢 **Pull Request #$PR_NUMBER Merged**
               \n
               \n
               # Title: $PR_TITLE
               \n
               **Author:** $PR_AUTHOR
               \n
               **URL:** $PR_URL
               \n
               **Description:** $PR_DESCRIPTION
               "}" \
               $DISCORD_WEBHOOK_URL
